-- ==============================================================================
-- VocabFlow Seed Data (5 General Licensed Demo Words for Testing)
-- Strictly adhering to copyright policies: No proprietary Oxford 3000 data.
-- ==============================================================================

insert into public.vocabularies (
  id,
  word,
  normalized_word,
  part_of_speech,
  cefr_level,
  definition_en,
  definition_th,
  example_sentence,
  example_translation_th,
  phonetic_uk,
  phonetic_us,
  audio_uk_url,
  audio_us_url,
  image_url,
  image_alt,
  topic,
  tags,
  source_name,
  source_license
) values
-- 1. Word: journey (A1)
(
  'a0000001-0000-0000-0000-000000000001',
  'journey',
  'journey',
  'noun',
  'A1',
  'An act of traveling from one place to another, especially over a long distance.',
  'การเดินทางจากที่หนึ่งไปยังอีกที่หนึ่ง',
  'We embarked on an exciting journey across the mountains.',
  'พวกเราเริ่มต้นการเดินทางที่น่าตื่นเต้นข้ามภูเขา',
  '/ˈdʒɜː.ni/',
  '/ˈdʒɝː.ni/',
  null,
  null,
  'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&auto=format&fit=crop&q=80',
  'Scenic road curving through breathtaking mountain vistas',
  'Travel & Nature',
  array['beginner', 'a1', 'travel'],
  'VocabFlow Open Demo Dataset',
  'CC-BY-4.0'
),
-- 2. Word: curious (A2)
(
  'a0000002-0000-0000-0000-000000000002',
  'curious',
  'curious',
  'adjective',
  'A2',
  'Eager to know or learn something new about the world.',
  'อยากรู้อยากเห็น หรือใฝ่รู้สิ่งใหม่ๆ',
  'Children are naturally curious and ask many interesting questions.',
  'เด็กๆ มักจะมีความอยากรู้อยากเห็นและถามคำถามที่น่าสนใจมากมาย',
  '/ˈkjʊə.ri.əs/',
  '/ˈkjʊr.i.əs/',
  null,
  null,
  'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80',
  'Open book with glasses reflecting cozy warm light',
  'Mind & Learning',
  array['a2', 'mindset', 'education'],
  'VocabFlow Open Demo Dataset',
  'CC-BY-4.0'
),
-- 3. Word: accomplish (B1)
(
  'a0000003-0000-0000-0000-000000000003',
  'accomplish',
  'accomplish',
  'verb',
  'B1',
  'To succeed in completing a task or achieving an objective.',
  'ทำสำเร็จ บรรลุผลตามเป้าหมาย',
  'You can accomplish your goals if you practice twenty minutes every day.',
  'คุณสามารถบรรลุเป้าหมายได้หากคุณฝึกฝนวันละ 20 นาทีเป็นประจำ',
  '/əˈkʌm.plɪʃ/',
  '/əˈkɑːm.plɪʃ/',
  null,
  null,
  'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&auto=format&fit=crop&q=80',
  'Colleagues celebrating team success with high-fives',
  'Achievement & Career',
  array['b1', 'success', 'work'],
  'VocabFlow Open Demo Dataset',
  'CC-BY-4.0'
),
-- 4. Word: resilient (B2)
(
  'a0000004-0000-0000-0000-000000000004',
  'resilient',
  'resilient',
  'adjective',
  'B2',
  'Able to withstand or recover quickly from difficult or stressful conditions.',
  'ยืดหยุ่น ล้มแล้วลุกเร็ว ฟื้นตัวได้ไว',
  'She showed a remarkably resilient mindset during tough times.',
  'เธอแสดงให้เห็นถึงกรอบความคิดที่ยืดหยุ่นและฟื้นตัวได้ดีในช่วงเวลาที่ยากลำบาก',
  '/rɪˈzɪl.jənt/',
  '/rɪˈzɪl.jənt/',
  null,
  null,
  'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
  'Vibrant green plant growing strongly from a stone crack',
  'Personal Growth',
  array['b2', 'mindset', 'psychology'],
  'VocabFlow Open Demo Dataset',
  'CC-BY-4.0'
),
-- 5. Word: persist (B2)
(
  'a0000005-0000-0000-0000-000000000005',
  'persist',
  'persist',
  'verb',
  'B2',
  'To continue firmly or steadily in an action despite difficulty or opposition.',
  'พากเพียร อดทนทำอย่างต่อเนื่องไม่ยอมแพ้',
  'If you persist with your daily flashcard habit, fluency will follow.',
  'หากคุณอดทนฝึกนิสัยการทบทวนแฟลชการ์ดทุกวัน ความคล่องแคล่วจะตามมาแน่นอน',
  '/pəˈsɪst/',
  '/pɚˈsɪst/',
  null,
  null,
  'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&auto=format&fit=crop&q=80',
  'Path leading through morning mist towards bright sunshine',
  'Habits & Discipline',
  array['b2', 'habit', 'perseverance'],
  'VocabFlow Open Demo Dataset',
  'CC-BY-4.0'
)
on conflict (id) do nothing;
