import { VocabularyWord } from "@/types/vocabulary";

export const INITIAL_VOCABULARY: VocabularyWord[] = [
  {
    id: "vocab-1",
    word: "serendipity",
    normalizedWord: "serendipity",
    partOfSpeech: "noun",
    cefrLevel: "C1",
    definition: "The occurrence and development of events by chance in a happy or beneficial way.",
    translation: "การพบสิ่งดีๆ โดยบังเอิญ หรือโชคลาภที่ไม่คาดฝัน",
    example: "A fortunate stroke of serendipity brought the two old friends together at the airport.",
    exampleTranslation: "ความบังเอิญที่โชคดีทำให้เพื่อนเก่าทั้งสองมาพบกันที่สนามบิน",
    phoneticUk: "/ˌser.ənˈdɪp.ə.ti/",
    phoneticUs: "/ˌser.ənˈdɪp.ə.t̬i/",
    imageUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600&auto=format&fit=crop&q=80",
    imageAlt: "Sunlight streaming through green leaves symbolizing pleasant surprises",
    topic: "Emotions & Mind",
    tags: ["advanced", "c1", "literature"],
    source: "Sample Licensed Vocabulary",
    license: "CC-BY-4.0",
  },
  {
    id: "vocab-2",
    word: "resilient",
    normalizedWord: "resilient",
    partOfSpeech: "adjective",
    cefrLevel: "B2",
    definition: "Able to withstand or recover quickly from difficult conditions.",
    translation: "ยืดหยุ่น ล้มแล้วลุกเร็ว ฟื้นตัวได้เร็ว",
    example: "She remained resilient despite facing numerous challenging setbacks.",
    exampleTranslation: "เธอยังคงเข้มแข็งและฟื้นตัวได้เร็วแม้ต้องเผชิญกับอุปสรรคมากมาย",
    phoneticUk: "/rɪˈzɪl.jənt/",
    phoneticUs: "/rɪˈzɪl.jənt/",
    imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    imageAlt: "Small green sprout growing tenaciously through stone",
    topic: "Personal Qualities",
    tags: ["b2", "mindset", "work"],
    source: "Sample Licensed Vocabulary",
    license: "CC-BY-4.0",
  },
  {
    id: "vocab-3",
    word: "accomplish",
    normalizedWord: "accomplish",
    partOfSpeech: "verb",
    cefrLevel: "B1",
    definition: "To succeed in doing or completing something.",
    translation: "ทำสำเร็จ บรรลุเป้าหมาย",
    example: "If we break down our study routine, we can accomplish all our goals this week.",
    exampleTranslation: "หากเราแบ่งตารางเวลาการเรียน เราจะสามารถบรรลุเป้าหมายทั้งหมดในสัปดาห์นี้ได้",
    phoneticUk: "/əˈkʌm.plɪʃ/",
    phoneticUs: "/əˈkɑːm.plɪʃ/",
    imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&auto=format&fit=crop&q=80",
    imageAlt: "Team celebrating achievement with high-fives",
    topic: "Achievement",
    tags: ["b1", "success", "work"],
    source: "Sample Licensed Vocabulary",
    license: "CC-BY-4.0",
  },
  {
    id: "vocab-4",
    word: "curious",
    normalizedWord: "curious",
    partOfSpeech: "adjective",
    cefrLevel: "A2",
    definition: "Eager to know or learn something.",
    translation: "อยากรู้อยากเห็น ใฝ่รู้ มีความกระตือรือร้นจะเรียนรู้",
    example: "Staying curious is one of the best habits for lifelong language mastery.",
    exampleTranslation: "การเป็นคนใฝ่รู้เป็นหนึ่งในนิสัยที่ดีที่สุดสำหรับการเชี่ยวชาญภาษาตลอดชีวิต",
    phoneticUk: "/ˈkjʊə.ri.əs/",
    phoneticUs: "/ˈkjʊr.i.əs/",
    imageUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80",
    imageAlt: "Open book with reading glasses in soft warm light",
    topic: "Learning",
    tags: ["a2", "personality", "daily"],
    source: "Sample Licensed Vocabulary",
    license: "CC-BY-4.0",
  },
  {
    id: "vocab-5",
    word: "journey",
    normalizedWord: "journey",
    partOfSpeech: "noun",
    cefrLevel: "A1",
    definition: "An act of traveling from one place to another.",
    translation: "การเดินทาง การก้าวไปข้างหน้า",
    example: "Every great language journey begins with just ten words a day.",
    exampleTranslation: "ทุกการเดินทางทางภาษาอันยิ่งใหญ่เริ่มต้นด้วยคำศัพท์เพียง 10 คำต่อวัน",
    phoneticUk: "/ˈdʒɜː.ni/",
    phoneticUs: "/ˈdʒɝː.ni/",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&auto=format&fit=crop&q=80",
    imageAlt: "Winding road leading towards scenic mountains",
    topic: "Travel",
    tags: ["a1", "travel", "beginner"],
    source: "Sample Licensed Vocabulary",
    license: "CC-BY-4.0",
  },
  {
    id: "vocab-6",
    word: "eloquent",
    normalizedWord: "eloquent",
    partOfSpeech: "adjective",
    cefrLevel: "C1",
    definition: "Fluent or persuasive in speaking or writing.",
    translation: "พูดจาคล่องแคล่ว โน้มน้าวใจ สละสลวย",
    example: "The speaker delivered an eloquent address that inspired everyone present.",
    exampleTranslation: "ผู้บรรยายได้กล่าวสุนทรพจน์ที่สละสลวยและสร้างแรงบันดาลใจให้ทุกคนที่อยู่ตรงนั้น",
    phoneticUk: "/ˈel.ə.kwənt/",
    phoneticUs: "/ˈel.ə.kwənt/",
    imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&auto=format&fit=crop&q=80",
    imageAlt: "Microphone on a podium in an auditorium",
    topic: "Communication",
    tags: ["c1", "speech", "formal"],
    source: "Sample Licensed Vocabulary",
    license: "CC-BY-4.0",
  },
];
